### ISSUE TITLE
Fails with perls < 5.22

### ISSUE THREAD

**Issue by andk** [vrurg/Pod-Weaver-Plugin-Include#1]
As per subject. Best illustrated with the matrix:

http://matrix.cpantesters.org/?dist=Pod-Weaver-Plugin-Include%20v0.1.8

Sample fail report:

http://www.cpantesters.org/cpan/report/4bee2a02-5280-11e8-9c6b-818fffe4da35

Diagnostics:

Unknown regexp modifier "/n" at /tmpfs/.cpan-build-cpansand/2018050800/Pod-Weaver-Plugin-Include-v0.1.8-10/blib/lib/Pod/Weaver/Plugin/Include/Finder.pm line 134, at end of line

If you want to keep the /n modifier (which was not supported prior 5.22), it would be cool if you could predeclare the dependency. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Thanks!

**Comment by vrurg** [comment]
Thanks for the report! I'm working on it right now, testing against 5.14+. Fixed version will be released tonight.

**Comment by vrurg** [comment]
Fixed in v0.1.9

Thanks!
